### ISSUE TITLE
Release 2.0.3.0 breaks backward compatibility

### ISSUE THREAD

**Issue by AJChapman** [haskell/double-conversion#30]
Version 2.0.2.0 has modules Data.Double.Conversion.ByteString and Data.Double.Conversion.Text (see https://hackage.haskell.org/package/double-conversion-2.0.2.0). But the new version has only Data.Double.Conversion.Convertable. This will break any package using double-conversion, and so should be a major version change (e.g. 2.1.0.0 or 3.0.0.0), if it was intended. See https://pvp.haskell.org/.

**Comment by Haskell-mouse** [comment]
I've done it and I am sorry. Now I am looking for a possible solution with Hakage.

**Comment by Haskell-mouse** [comment]
I've made a new minor release(2.0.4.0) with a compatibility layer. 
Formatting library is built with it successfully. 

Sorry for the inconvenience.

**Comment by sjakobi** [comment]
@Haskell-mouse Can you properly deprecate v2.0.3.0?!

Note that it also has a compatibility issue with `text`:

```
$ cabal install double-conversion-2.0.3.0 -w ghc-8.0.2
<...>
Data/Double/Conversion/Text.hs:48:52: error:
    Not in scope: ‘A.maBA’
    Module ‘Data.Text.Array’ does not export ‘maBA’.
```

**Comment by Haskell-mouse** [comment]
@sjakobi, done. 
Thanks for your update for `2.0.4.0`, but I've uploaded the `2.0.4.1` version which supports text 2.0. 
I've also got back the old function to the code and removed the upper bound for `bytestring` to allow using an old version of the library without overusing version-related pragmas and corresponding code duplication.

**Comment by Haskell-mouse** [comment]
@AJChapman, could I close the issue?

**Comment by AJChapman** [comment]
Yes, I think this is all good now. I had added a constraint to `formatting` to require `double-conversion >= 2.0.2.0 && < 2.0.3.0`. I'll now change it back to `double-conversion ^>= 2.0.2.0`. Thanks.
