### ISSUE TITLE
c-source must not have c++ source files in it

### ISSUE THREAD

**Issue by Kleidukos** [haskell/double-conversion#43]
c-source must not have c++ source files in it, these should go in cxx-sources.

see https://github.com/haskell/cabal/pull/9200

**Comment by Mikolaj** [comment]
Agreed. Let's discuss how best to make that change.

**Comment by sternenseemann** [comment]
I think a lot of downstream people will still run into this until a release with this fix is uploaded to hackage.

**Comment by Kleidukos** [comment]
@Haskell-mouse Do you think you could make a revision? :)

**Comment by Haskell-mouse** [comment]
> @Haskell-mouse Do you think you could make a revision? :)

@Kleidukos Yes, thanks for the remind. I am going to do this next week.

**Comment by sternenseemann** [comment]
> @Haskell-mouse Do you think you could make a revision? :)

This needs a new release, I believe. As far as I know Hackage forbids changing build related stanzas in a cabal file.

**Comment by Kleidukos** [comment]
Ah, well-spotted! I am not a big revisions user. :)

**Comment by andreasabel** [comment]
@Haskell-mouse : Friendly reminder that a release is needed.

Maybe it would also good to add a backup maintainer to the Hackage uploaders for this package, e.g. @Kleidukos .

**Comment by Kleidukos** [comment]
It would probably be better to introduce people who have knowledge and understanding of the library's domain, I know I don't.
