### ISSUE TITLE
New version with support for Cabal 3.10.2.0

### ISSUE THREAD

**Issue by Vekhir** [haskell/double-conversion#52]
In #44, the `double-conversion.cabal` was modified to replace the `c-sources` with `cxx-sources`. This was done in preparation/in response to [haskell/cabal#9200](https://github.com/haskell/cabal/pull/9200). The latter PR was merged into Cabal 3.10.2.0 and leads to build failures when using it to build `double-conversion` 2.0.4.2, as available on Hackage.

As the issue is already resolved on `master`, I ask you to make a new release to Hackage with the fix included.

-- Vekhir

**Comment by Kleidukos** [comment]
@Vekhir Hi, I don't have the power to upload a release to Hackage, we have to ask the current maintainers @bos and @Haskell-mouse :)

**Comment by Vekhir** [comment]
Oh, ok. Thanks for pinging them

**Comment by andreasabel** [comment]
I suppose this issue is also why `double-conversion` dropped out of Stackage: 
```
[8 of 8] Compiling Data.Double.Conversion.Text
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/cbits/hs-double-conversion-embed.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/bignum.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/bignum-dtoa.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/cached-powers.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/diy-fp.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/double-conversion.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/fast-dtoa.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/fixed-dtoa.o: No such file or directory
ar: .stack-work/dist/x86_64-osx/ghc-9.8.1/build/double-conversion/src/strtod.o: No such file or directory
```

**Comment by Haskell-mouse** [comment]
Sorry for the long wait. I've made the release.
